In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [54]:
import numpy as np
import pandas as pd

In [61]:
data=pd.read_csv("/content/gdrive/MyDrive/cleaned_data.csv")

In [62]:
data.head(15)#to see pattern in data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
3,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
4,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,Q
5,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S
6,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S
7,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C
8,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,S
9,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,S
10,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,S
11,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,S
12,18,1,2,"Williams, Mr. Charles Eugene",male,28.0,0,0,244373,13.0000,S
13,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,S
14,20,1,3,"Masselmani, Mrs. Fatima",female,28.0,0,0,2649,7.2250,C

In [63]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 718 entries, 0 to 717
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  718 non-null    int64
 1   Survived     718 non-null    int64
 2   Pclass       718 non-null    int64
 3   Name         718 non-null    object
 4   Sex          718 non-null    object
 5   Age          718 non-null    float64
 6   SibSp        718 non-null    int64
 7   Parch        718 non-null    int64
 8   Ticket       718 non-null    object
 9   Fare         718 non-null    float64
 10  Embarked     718 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 61.8+ KB

In [64]:
numeric_columns=['Age','Fare']#columns for which stats can be calculated

In [65]:
from scipy import stats

In [67]:
for col in numeric_columns:
  print(f"Summary Statistics for {col}:")
  print(f"Mean:{data[col].mean()}")
  print(f"Median:{data[col].median()}")
  print(f"Mode: {data[col].mode()[0]}")
  print(f"Standard Deviation:{data[col].std()}")
  print("\n")

Summary Statistics for Age:
Mean:28.079387186629525
Median:28.0
Mode: 28.0
Standard Deviation:10.01236856643464


Summary Statistics for Fare:
Mean:17.193203760445684
Median:11.75
Mode: 8.05
Standard Deviation:13.244507195747774

In [69]:
data[numeric_columns].describe()

              Age        Fare
count  718.000000  718.000000
mean    28.079387   17.193204
std     10.012369   13.244507
min      3.000000    0.000000
25%     22.000000    7.889575
50%     28.000000   11.750000
75%     32.875000   25.928150
max     54.000000   61.379200